branches:
  only:
    - master

language: ruby
rvm:
  - 2.1.1

bundler_args: --binstubs

script:
  # unit
  - rspec spec/application
  # test suite
  - rspec spec/simplify.rb --tag cloud

env:
  global:
    - secure: "f+M1CmnRs/JgZMhLTzgeOvPy9fe05E+Y66NRTFRWdzDnh7Ao0m3jT8bRZ17gHWTgCy05DgnGwYQcQcrPnoURymluytjwCziXegE6fu10Dm0F/oLDvTNxcflXaDCLMbyvNvL6JEff4bNVSFebfMtz5eUqKHU1s3lUOlX6lmqlIGk="
    - secure: "f6lrcSfGo6Nti5sdz7bU4IY0pw53zBWeJVhtytvZjKV+J4KG4f/0cDI81ZiJGHV0UHrPhrrcS17E+tT78qHWCAZbo4pbuXWUYYsKui9SZ5CGzdrz+wFB1q/IaBLFqgfhypiQL4f6Rx+1KlKAQe3BCO9RX2J8fiNM1ziSYwyq4jI="
    - secure: "A9goKvr6LcxFDYgMar3FRX7S5QhCv2aDINgRhl6O27to7a3WGJGgGEQGzEQgvJFNA+KiXNmWUDVJidRwfzl2rsXQt6Ou8bVU+hieD6UypKugfrevUlPHQ4Jq7UvDtnTJWxXgV/KNlQ6cBbKiFBaxLgfZqwma+Ml5fd5g6GmVXjs="

# notifications:
#   hipchat:
#     rooms:
#       # QA
#       - secure: "nbHfaQ6zvyb6up+Yc4ZZxrCRXGvo+cmTjZXMs+kVZubODHkWT+Q/+g2Qz4JkIhlnT3uFui4FamlqL3xSg9COa8xSwUgTsWxC2p0PMq15Kv6Ia37gtROteXyFMq3PtjRxnKBx6AG/97lj2HXzwVJPozE0wvFxswReepR+shU5RYA="
